# Generated by Django 4.0.3 on 2022-03-31 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projects',
            old_name='name',
            new_name='user_name',
        ),
        migrations.AddField(
            model_name='projects',
            name='project_full_desc',
            field=models.CharField(max_length=10000, null=True, verbose_name='Полное описание проекта'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='project_desc',
            field=models.CharField(max_length=500, null=True, verbose_name='Описание проекта'),
        ),
    ]
