# Generated by Django 4.0.3 on 2022-03-31 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_name_projects_user_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='active',
            field=models.CharField(max_length=10, null=True, verbose_name='Активна'),
        ),
    ]
