# Generated by Django 4.0.3 on 2022-04-04 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_account'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='country1',
            new_name='country',
        ),
    ]
