# Generated by Django 4.0.3 on 2022-04-04 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_account_city_account_phone_account_region_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='full_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
